function class = chooseClass()

label_str = classLabels();
class = listdlg('PromptString','Select a class:',...
                'SelectionMode','single',...
                'ListSize',[300,520],...
                'uh',30,...
                'ListString',label_str);
